name: Build, Notarize, and Add to Release

on:
  release:
    types: [published, prereleased]

jobs:
  build-and-release:
    name: Build, Notarize, and Add to Release
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Extract version from the release tag
      - name: Get Version from Tag
        id: versioning
        run: |
          # Extract version from the release tag
          TAG_NAME="${GITHUB_REF##*/}"
          VERSION="${TAG_NAME#v}" # Remove leading 'v' if present
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 3: Build the app
      - name: Build App
        run: |
          xcodebuild clean build \
            -project "VLC AndroidTV.xcodeproj" \
            -scheme "VLC AndroidTV" \
            -configuration Release \
            -archivePath "$PWD/build/VLC_AndroidTV.xcarchive" \
            archive

      # Step 4: Export the app
      - name: Export App
        run: |
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/VLC_AndroidTV.xcarchive" \
            -exportPath "$PWD/build" \
            -exportOptionsPlist "./ExportOptions.plist"

      # Step 5: Notarize the app
      - name: Notarize App
        env:
          AC_USERNAME: ${{ secrets.APPLE_ID }}
          AC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          xcrun altool --notarize-app \
            --primary-bundle-id "com.benlawrence.VLC-AndroidTV" \
            --username "$AC_USERNAME" \
            --password "$AC_PASSWORD" \
            --file "$PWD/build/VLC_AndroidTV.app"

      # Step 6: Create a .dmg file
      - name: Create DMG
        run: |
          # Install create-dmg if not already available
          brew install create-dmg || true

          # Package the app into a DMG
          create-dmg \
            --volname "VLC AndroidTV Installer" \
            --window-size 500 300 \
            --icon-size 100 \
            --app-drop-link 250 150 \
            --icon "VLC AndroidTV.app" 150 150 \
            "$PWD/build/VLC_AndroidTV.dmg" \
            "$PWD/build/VLC_AndroidTV.app"

      # Step 7: Upload the DMG to the release
      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "$PWD/build/VLC_AndroidTV.dmg"
          asset_name: "VLC_AndroidTV.dmg"
          asset_content_type: "application/octet-stream"
